/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedNovoRouteImport } from './routes/_authenticated/novo'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedGerencialRouteImport } from './routes/_authenticated/gerencial'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedOsRouteImport } from './routes/_authenticated/os'
import { Route as AuthenticatedDemandasRouteImport } from './routes/_authenticated/demandas'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated/contratos'
import { Route as AuthenticatedFechamentosRouteImport } from './routes/_authenticated/fechamentos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedVisitaIdRouteImport } from './routes/_authenticated/visita.$id'
import { Route as AuthenticatedProjetoIdRouteImport } from './routes/_authenticated/projeto.$id'
import { Route as AuthenticatedGerencialUsuariosRouteImport } from './routes/_authenticated/gerencial.usuarios'
import { Route as AuthenticatedClientesNovoRouteImport } from './routes/_authenticated/clientes.novo'
import { Route as AuthenticatedOsPainelRouteImport } from './routes/_authenticated/os.painel'
import { Route as AuthenticatedOsProgramacaoRouteImport } from './routes/_authenticated/os.programacao'
import { Route as AuthenticatedOsNovaRouteImport } from './routes/_authenticated/os.nova'
import { Route as AuthenticatedOsIdRouteImport } from './routes/_authenticated/os.$id'
import { Route as AuthenticatedDemandasNovaRouteImport } from './routes/_authenticated/demandas.nova'
import { Route as AuthenticatedDemandasImportarRouteImport } from './routes/_authenticated/demandas.importar'
import { Route as AuthenticatedDemandasIdRouteImport } from './routes/_authenticated/demandas.$id'
import { Route as AuthenticatedContratosNovoRouteImport } from './routes/_authenticated/contratos.novo'
import { Route as AuthenticatedContratosIdRouteImport } from './routes/_authenticated/contratos.$id'
import { Route as AuthenticatedFechamentosIdRouteImport } from './routes/_authenticated/fechamentos.$id'
import { Route as AuthenticatedClientesMigrarRouteImport } from './routes/_authenticated/clientes.migrar'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'
import { Route as AuthenticatedGerencialNovaRouteImport } from './routes/_authenticated/gerencial.nova'
import { Route as AuthenticatedVisitaIdReagendarRouteImport } from './routes/_authenticated/visita.$id.reagendar'
import { Route as AuthenticatedVisitaIdPagamentoRouteImport } from './routes/_authenticated/visita.$id.pagamento'
import { Route as AuthenticatedVisitaIdPendenteRouteImport } from './routes/_authenticated/visita.$id.pendente'
import { Route as AuthenticatedVisitaIdOrcamentoRouteImport } from './routes/_authenticated/visita.$id.orcamento'
import { Route as AuthenticatedVisitaIdOrcamentoIndexRouteImport } from './routes/_authenticated/visita.$id.orcamento.index'
import { Route as AuthenticatedVisitaIdOrcamentoPreEnvioRouteImport } from './routes/_authenticated/visita.$id.orcamento.pre-envio'
import { Route as AuthenticatedVisitaIdOrcamentoComplementosRouteImport } from './routes/_authenticated/visita.$id.orcamento.complementos'
import { Route as AuthenticatedVisitaIdOrcamentoCategoriasRouteImport } from './routes/_authenticated/visita.$id.orcamento.categorias'
import { Route as AuthenticatedGerencialVisitaIdEditarRouteImport } from './routes/_authenticated/gerencial.visita.$id.editar'
import { Route as AuthenticatedVisitaIdOrcamentoBlocosCatRouteImport } from './routes/_authenticated/visita.$id.orcamento.blocos.$cat'

const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovoRoute = AuthenticatedNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGerencialRoute = AuthenticatedGerencialRouteImport.update({
  id: '/gerencial',
  path: '/gerencial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisitaIdRoute = AuthenticatedVisitaIdRouteImport.update({
  id: '/visita/$id',
  path: '/visita/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetoIdRoute = AuthenticatedProjetoIdRouteImport.update({
  id: '/projeto/$id',
  path: '/projeto/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOsRoute = AuthenticatedOsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOsPainelRoute = AuthenticatedOsPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedOsRoute,
} as any)
const AuthenticatedOsProgramacaoRoute =
  AuthenticatedOsProgramacaoRouteImport.update({
    id: '/programacao',
    path: '/programacao',
    getParentRoute: () => AuthenticatedOsRoute,
  } as any)
const AuthenticatedOsNovaRoute = AuthenticatedOsNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AuthenticatedOsRoute,
} as any)
const AuthenticatedOsIdRoute = AuthenticatedOsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOsRoute,
} as any)
const AuthenticatedDemandasRoute = AuthenticatedDemandasRouteImport.update({
  id: '/demandas',
  path: '/demandas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemandasNovaRoute =
  AuthenticatedDemandasNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AuthenticatedDemandasRoute,
  } as any)
const AuthenticatedDemandasImportarRoute =
  AuthenticatedDemandasImportarRouteImport.update({
    id: '/importar',
    path: '/importar',
    getParentRoute: () => AuthenticatedDemandasRoute,
  } as any)
const AuthenticatedDemandasIdRoute = AuthenticatedDemandasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDemandasRoute,
} as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContratosNovoRoute =
  AuthenticatedContratosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedContratosRoute,
  } as any)
const AuthenticatedContratosIdRoute =
  AuthenticatedContratosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedContratosRoute,
  } as any)
const AuthenticatedFechamentosRoute =
  AuthenticatedFechamentosRouteImport.update({
    id: '/fechamentos',
    path: '/fechamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFechamentosIdRoute =
  AuthenticatedFechamentosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedFechamentosRoute,
  } as any)
const AuthenticatedClientesNovoRoute =
  AuthenticatedClientesNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const AuthenticatedClientesMigrarRoute =
  AuthenticatedClientesMigrarRouteImport.update({
    id: '/migrar',
    path: '/migrar',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientesRoute,
} as any)
const AuthenticatedGerencialUsuariosRoute =
  AuthenticatedGerencialUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedGerencialRoute,
  } as any)
const AuthenticatedGerencialNovaRoute =
  AuthenticatedGerencialNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AuthenticatedGerencialRoute,
  } as any)
const AuthenticatedVisitaIdReagendarRoute =
  AuthenticatedVisitaIdReagendarRouteImport.update({
    id: '/reagendar',
    path: '/reagendar',
    getParentRoute: () => AuthenticatedVisitaIdRoute,
  } as any)
const AuthenticatedVisitaIdPagamentoRoute =
  AuthenticatedVisitaIdPagamentoRouteImport.update({
    id: '/pagamento',
    path: '/pagamento',
    getParentRoute: () => AuthenticatedVisitaIdRoute,
  } as any)
const AuthenticatedVisitaIdPendenteRoute =
  AuthenticatedVisitaIdPendenteRouteImport.update({
    id: '/pendente',
    path: '/pendente',
    getParentRoute: () => AuthenticatedVisitaIdRoute,
  } as any)
const AuthenticatedVisitaIdOrcamentoRoute =
  AuthenticatedVisitaIdOrcamentoRouteImport.update({
    id: '/orcamento',
    path: '/orcamento',
    getParentRoute: () => AuthenticatedVisitaIdRoute,
  } as any)
const AuthenticatedVisitaIdOrcamentoIndexRoute =
  AuthenticatedVisitaIdOrcamentoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVisitaIdOrcamentoRoute,
  } as any)
const AuthenticatedVisitaIdOrcamentoPreEnvioRoute =
  AuthenticatedVisitaIdOrcamentoPreEnvioRouteImport.update({
    id: '/pre-envio',
    path: '/pre-envio',
    getParentRoute: () => AuthenticatedVisitaIdOrcamentoRoute,
  } as any)
const AuthenticatedVisitaIdOrcamentoComplementosRoute =
  AuthenticatedVisitaIdOrcamentoComplementosRouteImport.update({
    id: '/complementos',
    path: '/complementos',
    getParentRoute: () => AuthenticatedVisitaIdOrcamentoRoute,
  } as any)
const AuthenticatedVisitaIdOrcamentoCategoriasRoute =
  AuthenticatedVisitaIdOrcamentoCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedVisitaIdOrcamentoRoute,
  } as any)
const AuthenticatedGerencialVisitaIdEditarRoute =
  AuthenticatedGerencialVisitaIdEditarRouteImport.update({
    id: '/visita/$id/editar',
    path: '/visita/$id/editar',
    getParentRoute: () => AuthenticatedGerencialRoute,
  } as any)
const AuthenticatedVisitaIdOrcamentoBlocosCatRoute =
  AuthenticatedVisitaIdOrcamentoBlocosCatRouteImport.update({
    id: '/blocos/$cat',
    path: '/blocos/$cat',
    getParentRoute: () => AuthenticatedVisitaIdOrcamentoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demandas': typeof AuthenticatedDemandasRouteWithChildren
  '/contratos': typeof AuthenticatedContratosRouteWithChildren
  '/fechamentos': typeof AuthenticatedFechamentosRouteWithChildren
  '/gerencial': typeof AuthenticatedGerencialRouteWithChildren
  '/historico': typeof AuthenticatedHistoricoRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/novo': typeof AuthenticatedNovoRoute
  '/os': typeof AuthenticatedOsRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/clientes/migrar': typeof AuthenticatedClientesMigrarRoute
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/demandas/$id': typeof AuthenticatedDemandasIdRoute
  '/demandas/importar': typeof AuthenticatedDemandasImportarRoute
  '/demandas/nova': typeof AuthenticatedDemandasNovaRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/contratos/novo': typeof AuthenticatedContratosNovoRoute
  '/fechamentos/$id': typeof AuthenticatedFechamentosIdRoute
  '/gerencial/nova': typeof AuthenticatedGerencialNovaRoute
  '/gerencial/usuarios': typeof AuthenticatedGerencialUsuariosRoute
  '/os/$id': typeof AuthenticatedOsIdRoute
  '/os/nova': typeof AuthenticatedOsNovaRoute
  '/os/painel': typeof AuthenticatedOsPainelRoute
  '/os/programacao': typeof AuthenticatedOsProgramacaoRoute
  '/projeto/$id': typeof AuthenticatedProjetoIdRoute
  '/visita/$id': typeof AuthenticatedVisitaIdRouteWithChildren
  '/visita/$id/orcamento': typeof AuthenticatedVisitaIdOrcamentoRouteWithChildren
  '/visita/$id/pendente': typeof AuthenticatedVisitaIdPendenteRoute
  '/visita/$id/reagendar': typeof AuthenticatedVisitaIdReagendarRoute
  '/visita/$id/pagamento': typeof AuthenticatedVisitaIdPagamentoRoute
  '/gerencial/visita/$id/editar': typeof AuthenticatedGerencialVisitaIdEditarRoute
  '/visita/$id/orcamento/categorias': typeof AuthenticatedVisitaIdOrcamentoCategoriasRoute
  '/visita/$id/orcamento/pre-envio': typeof AuthenticatedVisitaIdOrcamentoPreEnvioRoute
  '/visita/$id/orcamento/complementos': typeof AuthenticatedVisitaIdOrcamentoComplementosRoute
  '/visita/$id/orcamento/': typeof AuthenticatedVisitaIdOrcamentoIndexRoute
  '/visita/$id/orcamento/blocos/$cat': typeof AuthenticatedVisitaIdOrcamentoBlocosCatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demandas': typeof AuthenticatedDemandasRouteWithChildren
  '/contratos': typeof AuthenticatedContratosRouteWithChildren
  '/fechamentos': typeof AuthenticatedFechamentosRouteWithChildren
  '/gerencial': typeof AuthenticatedGerencialRouteWithChildren
  '/historico': typeof AuthenticatedHistoricoRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/novo': typeof AuthenticatedNovoRoute
  '/os': typeof AuthenticatedOsRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/clientes/migrar': typeof AuthenticatedClientesMigrarRoute
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/demandas/$id': typeof AuthenticatedDemandasIdRoute
  '/demandas/importar': typeof AuthenticatedDemandasImportarRoute
  '/demandas/nova': typeof AuthenticatedDemandasNovaRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/contratos/novo': typeof AuthenticatedContratosNovoRoute
  '/fechamentos/$id': typeof AuthenticatedFechamentosIdRoute
  '/gerencial/nova': typeof AuthenticatedGerencialNovaRoute
  '/gerencial/usuarios': typeof AuthenticatedGerencialUsuariosRoute
  '/os/$id': typeof AuthenticatedOsIdRoute
  '/os/nova': typeof AuthenticatedOsNovaRoute
  '/os/painel': typeof AuthenticatedOsPainelRoute
  '/os/programacao': typeof AuthenticatedOsProgramacaoRoute
  '/projeto/$id': typeof AuthenticatedProjetoIdRoute
  '/visita/$id': typeof AuthenticatedVisitaIdRouteWithChildren
  '/visita/$id/pendente': typeof AuthenticatedVisitaIdPendenteRoute
  '/visita/$id/reagendar': typeof AuthenticatedVisitaIdReagendarRoute
  '/visita/$id/pagamento': typeof AuthenticatedVisitaIdPagamentoRoute
  '/gerencial/visita/$id/editar': typeof AuthenticatedGerencialVisitaIdEditarRoute
  '/visita/$id/orcamento/categorias': typeof AuthenticatedVisitaIdOrcamentoCategoriasRoute
  '/visita/$id/orcamento/pre-envio': typeof AuthenticatedVisitaIdOrcamentoPreEnvioRoute
  '/visita/$id/orcamento/complementos': typeof AuthenticatedVisitaIdOrcamentoComplementosRoute
  '/visita/$id/orcamento': typeof AuthenticatedVisitaIdOrcamentoIndexRoute
  '/visita/$id/orcamento/blocos/$cat': typeof AuthenticatedVisitaIdOrcamentoBlocosCatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/demandas': typeof AuthenticatedDemandasRouteWithChildren
  '/_authenticated/contratos': typeof AuthenticatedContratosRouteWithChildren
  '/_authenticated/fechamentos': typeof AuthenticatedFechamentosRouteWithChildren
  '/_authenticated/gerencial': typeof AuthenticatedGerencialRouteWithChildren
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/novo': typeof AuthenticatedNovoRoute
  '/_authenticated/os': typeof AuthenticatedOsRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/clientes/migrar': typeof AuthenticatedClientesMigrarRoute
  '/_authenticated/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/_authenticated/demandas/$id': typeof AuthenticatedDemandasIdRoute
  '/_authenticated/demandas/importar': typeof AuthenticatedDemandasImportarRoute
  '/_authenticated/demandas/nova': typeof AuthenticatedDemandasNovaRoute
  '/_authenticated/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/_authenticated/contratos/novo': typeof AuthenticatedContratosNovoRoute
  '/_authenticated/fechamentos/$id': typeof AuthenticatedFechamentosIdRoute
  '/_authenticated/gerencial/nova': typeof AuthenticatedGerencialNovaRoute
  '/_authenticated/gerencial/usuarios': typeof AuthenticatedGerencialUsuariosRoute
  '/_authenticated/os/$id': typeof AuthenticatedOsIdRoute
  '/_authenticated/os/nova': typeof AuthenticatedOsNovaRoute
  '/_authenticated/os/painel': typeof AuthenticatedOsPainelRoute
  '/_authenticated/os/programacao': typeof AuthenticatedOsProgramacaoRoute
  '/_authenticated/projeto/$id': typeof AuthenticatedProjetoIdRoute
  '/_authenticated/visita/$id': typeof AuthenticatedVisitaIdRouteWithChildren
  '/_authenticated/visita/$id/orcamento': typeof AuthenticatedVisitaIdOrcamentoRouteWithChildren
  '/_authenticated/visita/$id/pendente': typeof AuthenticatedVisitaIdPendenteRoute
  '/_authenticated/visita/$id/reagendar': typeof AuthenticatedVisitaIdReagendarRoute
  '/_authenticated/visita/$id/pagamento': typeof AuthenticatedVisitaIdPagamentoRoute
  '/_authenticated/gerencial/visita/$id/editar': typeof AuthenticatedGerencialVisitaIdEditarRoute
  '/_authenticated/visita/$id/orcamento/categorias': typeof AuthenticatedVisitaIdOrcamentoCategoriasRoute
  '/_authenticated/visita/$id/orcamento/pre-envio': typeof AuthenticatedVisitaIdOrcamentoPreEnvioRoute
  '/_authenticated/visita/$id/orcamento/complementos': typeof AuthenticatedVisitaIdOrcamentoComplementosRoute
  '/_authenticated/visita/$id/orcamento/': typeof AuthenticatedVisitaIdOrcamentoIndexRoute
  '/_authenticated/visita/$id/orcamento/blocos/$cat': typeof AuthenticatedVisitaIdOrcamentoBlocosCatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/redefinir-senha'
    | '/admin'
    | '/calendario'
    | '/clientes'
    | '/dashboard'
    | '/demandas'
    | '/contratos'
    | '/fechamentos'
    | '/gerencial'
    | '/historico'
    | '/mapa'
    | '/novo'
    | '/os'
    | '/perfil'
    | '/clientes/$id'
    | '/clientes/migrar'
    | '/clientes/novo'
    | '/demandas/$id'
    | '/demandas/importar'
    | '/demandas/nova'
    | '/contratos/$id'
    | '/contratos/novo'
    | '/fechamentos/$id'
    | '/gerencial/nova'
    | '/gerencial/usuarios'
    | '/os/$id'
    | '/os/nova'
    | '/os/painel'
    | '/os/programacao'
    | '/projeto/$id'
    | '/visita/$id'
    | '/visita/$id/orcamento'
    | '/visita/$id/pendente'
    | '/visita/$id/reagendar'
    | '/visita/$id/pagamento'
    | '/gerencial/visita/$id/editar'
    | '/visita/$id/orcamento/categorias'
    | '/visita/$id/orcamento/pre-envio'
    | '/visita/$id/orcamento/complementos'
    | '/visita/$id/orcamento/'
    | '/visita/$id/orcamento/blocos/$cat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/redefinir-senha'
    | '/admin'
    | '/calendario'
    | '/clientes'
    | '/dashboard'
    | '/demandas'
    | '/contratos'
    | '/fechamentos'
    | '/gerencial'
    | '/historico'
    | '/mapa'
    | '/novo'
    | '/os'
    | '/perfil'
    | '/clientes/$id'
    | '/clientes/migrar'
    | '/clientes/novo'
    | '/demandas/$id'
    | '/demandas/importar'
    | '/demandas/nova'
    | '/contratos/$id'
    | '/contratos/novo'
    | '/fechamentos/$id'
    | '/gerencial/nova'
    | '/gerencial/usuarios'
    | '/os/$id'
    | '/os/nova'
    | '/os/painel'
    | '/os/programacao'
    | '/projeto/$id'
    | '/visita/$id'
    | '/visita/$id/pendente'
    | '/visita/$id/reagendar'
    | '/visita/$id/pagamento'
    | '/gerencial/visita/$id/editar'
    | '/visita/$id/orcamento/categorias'
    | '/visita/$id/orcamento/pre-envio'
    | '/visita/$id/orcamento/complementos'
    | '/visita/$id/orcamento'
    | '/visita/$id/orcamento/blocos/$cat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/redefinir-senha'
    | '/_authenticated/admin'
    | '/_authenticated/calendario'
    | '/_authenticated/clientes'
    | '/_authenticated/dashboard'
    | '/_authenticated/demandas'
    | '/_authenticated/contratos'
    | '/_authenticated/fechamentos'
    | '/_authenticated/gerencial'
    | '/_authenticated/historico'
    | '/_authenticated/mapa'
    | '/_authenticated/novo'
    | '/_authenticated/os'
    | '/_authenticated/perfil'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/clientes/migrar'
    | '/_authenticated/clientes/novo'
    | '/_authenticated/demandas/$id'
    | '/_authenticated/demandas/importar'
    | '/_authenticated/demandas/nova'
    | '/_authenticated/contratos/$id'
    | '/_authenticated/contratos/novo'
    | '/_authenticated/fechamentos/$id'
    | '/_authenticated/gerencial/nova'
    | '/_authenticated/gerencial/usuarios'
    | '/_authenticated/os/$id'
    | '/_authenticated/os/nova'
    | '/_authenticated/os/painel'
    | '/_authenticated/os/programacao'
    | '/_authenticated/projeto/$id'
    | '/_authenticated/visita/$id'
    | '/_authenticated/visita/$id/orcamento'
    | '/_authenticated/visita/$id/pendente'
    | '/_authenticated/visita/$id/reagendar'
    | '/_authenticated/visita/$id/pagamento'
    | '/_authenticated/gerencial/visita/$id/editar'
    | '/_authenticated/visita/$id/orcamento/categorias'
    | '/_authenticated/visita/$id/orcamento/pre-envio'
    | '/_authenticated/visita/$id/orcamento/complementos'
    | '/_authenticated/visita/$id/orcamento/'
    | '/_authenticated/visita/$id/orcamento/blocos/$cat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/novo': {
      id: '/_authenticated/novo'
      path: '/novo'
      fullPath: '/novo'
      preLoaderRoute: typeof AuthenticatedNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gerencial': {
      id: '/_authenticated/gerencial'
      path: '/gerencial'
      fullPath: '/gerencial'
      preLoaderRoute: typeof AuthenticatedGerencialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/os': {
      id: '/_authenticated/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof AuthenticatedOsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/os/nova': {
      id: '/_authenticated/os/nova'
      path: '/nova'
      fullPath: '/os/nova'
      preLoaderRoute: typeof AuthenticatedOsNovaRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/painel': {
      id: '/_authenticated/os/painel'
      path: '/painel'
      fullPath: '/os/painel'
      preLoaderRoute: typeof AuthenticatedOsPainelRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/programacao': {
      id: '/_authenticated/os/programacao'
      path: '/programacao'
      fullPath: '/os/programacao'
      preLoaderRoute: typeof AuthenticatedOsProgramacaoRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/$id': {
      id: '/_authenticated/os/$id'
      path: '/$id'
      fullPath: '/os/$id'
      preLoaderRoute: typeof AuthenticatedOsIdRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/demandas': {
      id: '/_authenticated/demandas'
      path: '/demandas'
      fullPath: '/demandas'
      preLoaderRoute: typeof AuthenticatedDemandasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandas/nova': {
      id: '/_authenticated/demandas/nova'
      path: '/nova'
      fullPath: '/demandas/nova'
      preLoaderRoute: typeof AuthenticatedDemandasNovaRouteImport
      parentRoute: typeof AuthenticatedDemandasRoute
    }
    '/_authenticated/demandas/importar': {
      id: '/_authenticated/demandas/importar'
      path: '/importar'
      fullPath: '/demandas/importar'
      preLoaderRoute: typeof AuthenticatedDemandasImportarRouteImport
      parentRoute: typeof AuthenticatedDemandasRoute
    }
    '/_authenticated/demandas/$id': {
      id: '/_authenticated/demandas/$id'
      path: '/$id'
      fullPath: '/demandas/$id'
      preLoaderRoute: typeof AuthenticatedDemandasIdRouteImport
      parentRoute: typeof AuthenticatedDemandasRoute
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/novo': {
      id: '/_authenticated/contratos/novo'
      path: '/novo'
      fullPath: '/contratos/novo'
      preLoaderRoute: typeof AuthenticatedContratosNovoRouteImport
      parentRoute: typeof AuthenticatedContratosRoute
    }
    '/_authenticated/contratos/$id': {
      id: '/_authenticated/contratos/$id'
      path: '/$id'
      fullPath: '/contratos/$id'
      preLoaderRoute: typeof AuthenticatedContratosIdRouteImport
      parentRoute: typeof AuthenticatedContratosRoute
    }
    '/_authenticated/fechamentos': {
      id: '/_authenticated/fechamentos'
      path: '/fechamentos'
      fullPath: '/fechamentos'
      preLoaderRoute: typeof AuthenticatedFechamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fechamentos/$id': {
      id: '/_authenticated/fechamentos/$id'
      path: '/$id'
      fullPath: '/fechamentos/$id'
      preLoaderRoute: typeof AuthenticatedFechamentosIdRouteImport
      parentRoute: typeof AuthenticatedFechamentosRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/novo': {
      id: '/_authenticated/clientes/novo'
      path: '/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AuthenticatedClientesNovoRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/clientes/migrar': {
      id: '/_authenticated/clientes/migrar'
      path: '/migrar'
      fullPath: '/clientes/migrar'
      preLoaderRoute: typeof AuthenticatedClientesMigrarRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visita/$id': {
      id: '/_authenticated/visita/$id'
      path: '/visita/$id'
      fullPath: '/visita/$id'
      preLoaderRoute: typeof AuthenticatedVisitaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projeto/$id': {
      id: '/_authenticated/projeto/$id'
      path: '/projeto/$id'
      fullPath: '/projeto/$id'
      preLoaderRoute: typeof AuthenticatedProjetoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gerencial/usuarios': {
      id: '/_authenticated/gerencial/usuarios'
      path: '/usuarios'
      fullPath: '/gerencial/usuarios'
      preLoaderRoute: typeof AuthenticatedGerencialUsuariosRouteImport
      parentRoute: typeof AuthenticatedGerencialRoute
    }
    '/_authenticated/gerencial/nova': {
      id: '/_authenticated/gerencial/nova'
      path: '/nova'
      fullPath: '/gerencial/nova'
      preLoaderRoute: typeof AuthenticatedGerencialNovaRouteImport
      parentRoute: typeof AuthenticatedGerencialRoute
    }
    '/_authenticated/visita/$id/reagendar': {
      id: '/_authenticated/visita/$id/reagendar'
      path: '/reagendar'
      fullPath: '/visita/$id/reagendar'
      preLoaderRoute: typeof AuthenticatedVisitaIdReagendarRouteImport
      parentRoute: typeof AuthenticatedVisitaIdRoute
    }
    '/_authenticated/visita/$id/pagamento': {
      id: '/_authenticated/visita/$id/pagamento'
      path: '/pagamento'
      fullPath: '/visita/$id/pagamento'
      preLoaderRoute: typeof AuthenticatedVisitaIdPagamentoRouteImport
      parentRoute: typeof AuthenticatedVisitaIdRoute
    }
    '/_authenticated/visita/$id/pendente': {
      id: '/_authenticated/visita/$id/pendente'
      path: '/pendente'
      fullPath: '/visita/$id/pendente'
      preLoaderRoute: typeof AuthenticatedVisitaIdPendenteRouteImport
      parentRoute: typeof AuthenticatedVisitaIdRoute
    }
    '/_authenticated/visita/$id/orcamento': {
      id: '/_authenticated/visita/$id/orcamento'
      path: '/orcamento'
      fullPath: '/visita/$id/orcamento'
      preLoaderRoute: typeof AuthenticatedVisitaIdOrcamentoRouteImport
      parentRoute: typeof AuthenticatedVisitaIdRoute
    }
    '/_authenticated/visita/$id/orcamento/': {
      id: '/_authenticated/visita/$id/orcamento/'
      path: '/'
      fullPath: '/visita/$id/orcamento/'
      preLoaderRoute: typeof AuthenticatedVisitaIdOrcamentoIndexRouteImport
      parentRoute: typeof AuthenticatedVisitaIdOrcamentoRoute
    }
    '/_authenticated/visita/$id/orcamento/pre-envio': {
      id: '/_authenticated/visita/$id/orcamento/pre-envio'
      path: '/pre-envio'
      fullPath: '/visita/$id/orcamento/pre-envio'
      preLoaderRoute: typeof AuthenticatedVisitaIdOrcamentoPreEnvioRouteImport
      parentRoute: typeof AuthenticatedVisitaIdOrcamentoRoute
    }
    '/_authenticated/visita/$id/orcamento/complementos': {
      id: '/_authenticated/visita/$id/orcamento/complementos'
      path: '/complementos'
      fullPath: '/visita/$id/orcamento/complementos'
      preLoaderRoute: typeof AuthenticatedVisitaIdOrcamentoComplementosRouteImport
      parentRoute: typeof AuthenticatedVisitaIdOrcamentoRoute
    }
    '/_authenticated/visita/$id/orcamento/categorias': {
      id: '/_authenticated/visita/$id/orcamento/categorias'
      path: '/categorias'
      fullPath: '/visita/$id/orcamento/categorias'
      preLoaderRoute: typeof AuthenticatedVisitaIdOrcamentoCategoriasRouteImport
      parentRoute: typeof AuthenticatedVisitaIdOrcamentoRoute
    }
    '/_authenticated/gerencial/visita/$id/editar': {
      id: '/_authenticated/gerencial/visita/$id/editar'
      path: '/visita/$id/editar'
      fullPath: '/gerencial/visita/$id/editar'
      preLoaderRoute: typeof AuthenticatedGerencialVisitaIdEditarRouteImport
      parentRoute: typeof AuthenticatedGerencialRoute
    }
    '/_authenticated/visita/$id/orcamento/blocos/$cat': {
      id: '/_authenticated/visita/$id/orcamento/blocos/$cat'
      path: '/blocos/$cat'
      fullPath: '/visita/$id/orcamento/blocos/$cat'
      preLoaderRoute: typeof AuthenticatedVisitaIdOrcamentoBlocosCatRouteImport
      parentRoute: typeof AuthenticatedVisitaIdOrcamentoRoute
    }
  }
}

interface AuthenticatedOsRouteChildren {
  AuthenticatedOsIdRoute: typeof AuthenticatedOsIdRoute
  AuthenticatedOsNovaRoute: typeof AuthenticatedOsNovaRoute
  AuthenticatedOsPainelRoute: typeof AuthenticatedOsPainelRoute
  AuthenticatedOsProgramacaoRoute: typeof AuthenticatedOsProgramacaoRoute
}

const AuthenticatedOsRouteChildren: AuthenticatedOsRouteChildren = {
  AuthenticatedOsIdRoute: AuthenticatedOsIdRoute,
  AuthenticatedOsNovaRoute: AuthenticatedOsNovaRoute,
  AuthenticatedOsPainelRoute: AuthenticatedOsPainelRoute,
  AuthenticatedOsProgramacaoRoute: AuthenticatedOsProgramacaoRoute,
}

const AuthenticatedOsRouteWithChildren =
  AuthenticatedOsRoute._addFileChildren(AuthenticatedOsRouteChildren)

interface AuthenticatedDemandasRouteChildren {
  AuthenticatedDemandasIdRoute: typeof AuthenticatedDemandasIdRoute
  AuthenticatedDemandasImportarRoute: typeof AuthenticatedDemandasImportarRoute
  AuthenticatedDemandasNovaRoute: typeof AuthenticatedDemandasNovaRoute
}

const AuthenticatedDemandasRouteChildren: AuthenticatedDemandasRouteChildren = {
  AuthenticatedDemandasIdRoute: AuthenticatedDemandasIdRoute,
  AuthenticatedDemandasImportarRoute: AuthenticatedDemandasImportarRoute,
  AuthenticatedDemandasNovaRoute: AuthenticatedDemandasNovaRoute,
}

const AuthenticatedDemandasRouteWithChildren =
  AuthenticatedDemandasRoute._addFileChildren(AuthenticatedDemandasRouteChildren)

interface AuthenticatedContratosRouteChildren {
  AuthenticatedContratosIdRoute: typeof AuthenticatedContratosIdRoute
  AuthenticatedContratosNovoRoute: typeof AuthenticatedContratosNovoRoute
}

const AuthenticatedContratosRouteChildren: AuthenticatedContratosRouteChildren =
  {
    AuthenticatedContratosIdRoute: AuthenticatedContratosIdRoute,
    AuthenticatedContratosNovoRoute: AuthenticatedContratosNovoRoute,
  }

const AuthenticatedContratosRouteWithChildren =
  AuthenticatedContratosRoute._addFileChildren(
    AuthenticatedContratosRouteChildren,
  )

interface AuthenticatedFechamentosRouteChildren {
  AuthenticatedFechamentosIdRoute: typeof AuthenticatedFechamentosIdRoute
}

const AuthenticatedFechamentosRouteChildren: AuthenticatedFechamentosRouteChildren =
  {
    AuthenticatedFechamentosIdRoute: AuthenticatedFechamentosIdRoute,
  }

const AuthenticatedFechamentosRouteWithChildren =
  AuthenticatedFechamentosRoute._addFileChildren(
    AuthenticatedFechamentosRouteChildren,
  )

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedClientesMigrarRoute: typeof AuthenticatedClientesMigrarRoute
  AuthenticatedClientesNovoRoute: typeof AuthenticatedClientesNovoRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedClientesMigrarRoute: AuthenticatedClientesMigrarRoute,
  AuthenticatedClientesNovoRoute: AuthenticatedClientesNovoRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedGerencialRouteChildren {
  AuthenticatedGerencialNovaRoute: typeof AuthenticatedGerencialNovaRoute
  AuthenticatedGerencialUsuariosRoute: typeof AuthenticatedGerencialUsuariosRoute
  AuthenticatedGerencialVisitaIdEditarRoute: typeof AuthenticatedGerencialVisitaIdEditarRoute
}

const AuthenticatedGerencialRouteChildren: AuthenticatedGerencialRouteChildren =
  {
    AuthenticatedGerencialNovaRoute: AuthenticatedGerencialNovaRoute,
    AuthenticatedGerencialUsuariosRoute: AuthenticatedGerencialUsuariosRoute,
    AuthenticatedGerencialVisitaIdEditarRoute:
      AuthenticatedGerencialVisitaIdEditarRoute,
  }

const AuthenticatedGerencialRouteWithChildren =
  AuthenticatedGerencialRoute._addFileChildren(
    AuthenticatedGerencialRouteChildren,
  )

interface AuthenticatedVisitaIdOrcamentoRouteChildren {
  AuthenticatedVisitaIdOrcamentoCategoriasRoute: typeof AuthenticatedVisitaIdOrcamentoCategoriasRoute
  AuthenticatedVisitaIdOrcamentoPreEnvioRoute: typeof AuthenticatedVisitaIdOrcamentoPreEnvioRoute
  AuthenticatedVisitaIdOrcamentoComplementosRoute: typeof AuthenticatedVisitaIdOrcamentoComplementosRoute
  AuthenticatedVisitaIdOrcamentoIndexRoute: typeof AuthenticatedVisitaIdOrcamentoIndexRoute
  AuthenticatedVisitaIdOrcamentoBlocosCatRoute: typeof AuthenticatedVisitaIdOrcamentoBlocosCatRoute
}

const AuthenticatedVisitaIdOrcamentoRouteChildren: AuthenticatedVisitaIdOrcamentoRouteChildren =
  {
    AuthenticatedVisitaIdOrcamentoCategoriasRoute:
      AuthenticatedVisitaIdOrcamentoCategoriasRoute,
    AuthenticatedVisitaIdOrcamentoPreEnvioRoute:
      AuthenticatedVisitaIdOrcamentoPreEnvioRoute,
    AuthenticatedVisitaIdOrcamentoComplementosRoute:
      AuthenticatedVisitaIdOrcamentoComplementosRoute,
    AuthenticatedVisitaIdOrcamentoIndexRoute:
      AuthenticatedVisitaIdOrcamentoIndexRoute,
    AuthenticatedVisitaIdOrcamentoBlocosCatRoute:
      AuthenticatedVisitaIdOrcamentoBlocosCatRoute,
  }

const AuthenticatedVisitaIdOrcamentoRouteWithChildren =
  AuthenticatedVisitaIdOrcamentoRoute._addFileChildren(
    AuthenticatedVisitaIdOrcamentoRouteChildren,
  )

interface AuthenticatedVisitaIdRouteChildren {
  AuthenticatedVisitaIdOrcamentoRoute: typeof AuthenticatedVisitaIdOrcamentoRouteWithChildren
  AuthenticatedVisitaIdPendenteRoute: typeof AuthenticatedVisitaIdPendenteRoute
  AuthenticatedVisitaIdReagendarRoute: typeof AuthenticatedVisitaIdReagendarRoute
  AuthenticatedVisitaIdPagamentoRoute: typeof AuthenticatedVisitaIdPagamentoRoute
}

const AuthenticatedVisitaIdRouteChildren: AuthenticatedVisitaIdRouteChildren = {
  AuthenticatedVisitaIdOrcamentoRoute:
    AuthenticatedVisitaIdOrcamentoRouteWithChildren,
  AuthenticatedVisitaIdPendenteRoute: AuthenticatedVisitaIdPendenteRoute,
  AuthenticatedVisitaIdReagendarRoute: AuthenticatedVisitaIdReagendarRoute,
  AuthenticatedVisitaIdPagamentoRoute: AuthenticatedVisitaIdPagamentoRoute,
}

const AuthenticatedVisitaIdRouteWithChildren =
  AuthenticatedVisitaIdRoute._addFileChildren(
    AuthenticatedVisitaIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDemandasRoute: typeof AuthenticatedDemandasRouteWithChildren
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRouteWithChildren
  AuthenticatedFechamentosRoute: typeof AuthenticatedFechamentosRouteWithChildren
  AuthenticatedGerencialRoute: typeof AuthenticatedGerencialRouteWithChildren
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedNovoRoute: typeof AuthenticatedNovoRoute
  AuthenticatedOsRoute: typeof AuthenticatedOsRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProjetoIdRoute: typeof AuthenticatedProjetoIdRoute
  AuthenticatedVisitaIdRoute: typeof AuthenticatedVisitaIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDemandasRoute: AuthenticatedDemandasRouteWithChildren,
  AuthenticatedContratosRoute: AuthenticatedContratosRouteWithChildren,
  AuthenticatedFechamentosRoute: AuthenticatedFechamentosRouteWithChildren,
  AuthenticatedGerencialRoute: AuthenticatedGerencialRouteWithChildren,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedNovoRoute: AuthenticatedNovoRoute,
  AuthenticatedOsRoute: AuthenticatedOsRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProjetoIdRoute: AuthenticatedProjetoIdRoute,
  AuthenticatedVisitaIdRoute: AuthenticatedVisitaIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
