/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedNovoRouteImport } from './routes/_authenticated/novo'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedGerencialRouteImport } from './routes/_authenticated/gerencial'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedVisitaIdRouteImport } from './routes/_authenticated/visita.$id'
import { Route as AuthenticatedProjetoIdRouteImport } from './routes/_authenticated/projeto.$id'
import { Route as AuthenticatedGerencialNovaRouteImport } from './routes/_authenticated/gerencial.nova'
import { Route as AuthenticatedVisitaIdOrcamentoRouteImport } from './routes/_authenticated/visita.$id.orcamento'
import { Route as AuthenticatedVisitaIdOrcamentoCategoriasRouteImport } from './routes/_authenticated/visita.$id.orcamento.categorias'
import { Route as AuthenticatedGerencialVisitaIdEditarRouteImport } from './routes/_authenticated/gerencial.visita.$id.editar'
import { Route as AuthenticatedVisitaIdOrcamentoBlocosCatRouteImport } from './routes/_authenticated/visita.$id.orcamento.blocos.$cat'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovoRoute = AuthenticatedNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGerencialRoute = AuthenticatedGerencialRouteImport.update({
  id: '/gerencial',
  path: '/gerencial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisitaIdRoute = AuthenticatedVisitaIdRouteImport.update({
  id: '/visita/$id',
  path: '/visita/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetoIdRoute = AuthenticatedProjetoIdRouteImport.update({
  id: '/projeto/$id',
  path: '/projeto/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGerencialNovaRoute =
  AuthenticatedGerencialNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AuthenticatedGerencialRoute,
  } as any)
const AuthenticatedVisitaIdOrcamentoRoute =
  AuthenticatedVisitaIdOrcamentoRouteImport.update({
    id: '/orcamento',
    path: '/orcamento',
    getParentRoute: () => AuthenticatedVisitaIdRoute,
  } as any)
const AuthenticatedVisitaIdOrcamentoCategoriasRoute =
  AuthenticatedVisitaIdOrcamentoCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedVisitaIdOrcamentoRoute,
  } as any)
const AuthenticatedGerencialVisitaIdEditarRoute =
  AuthenticatedGerencialVisitaIdEditarRouteImport.update({
    id: '/visita/$id/editar',
    path: '/visita/$id/editar',
    getParentRoute: () => AuthenticatedGerencialRoute,
  } as any)
const AuthenticatedVisitaIdOrcamentoBlocosCatRoute =
  AuthenticatedVisitaIdOrcamentoBlocosCatRouteImport.update({
    id: '/blocos/$cat',
    path: '/blocos/$cat',
    getParentRoute: () => AuthenticatedVisitaIdOrcamentoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gerencial': typeof AuthenticatedGerencialRouteWithChildren
  '/mapa': typeof AuthenticatedMapaRoute
  '/novo': typeof AuthenticatedNovoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/gerencial/nova': typeof AuthenticatedGerencialNovaRoute
  '/projeto/$id': typeof AuthenticatedProjetoIdRoute
  '/visita/$id': typeof AuthenticatedVisitaIdRouteWithChildren
  '/visita/$id/orcamento': typeof AuthenticatedVisitaIdOrcamentoRouteWithChildren
  '/gerencial/visita/$id/editar': typeof AuthenticatedGerencialVisitaIdEditarRoute
  '/visita/$id/orcamento/categorias': typeof AuthenticatedVisitaIdOrcamentoCategoriasRoute
  '/visita/$id/orcamento/blocos/$cat': typeof AuthenticatedVisitaIdOrcamentoBlocosCatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gerencial': typeof AuthenticatedGerencialRouteWithChildren
  '/mapa': typeof AuthenticatedMapaRoute
  '/novo': typeof AuthenticatedNovoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/gerencial/nova': typeof AuthenticatedGerencialNovaRoute
  '/projeto/$id': typeof AuthenticatedProjetoIdRoute
  '/visita/$id': typeof AuthenticatedVisitaIdRouteWithChildren
  '/visita/$id/orcamento': typeof AuthenticatedVisitaIdOrcamentoRouteWithChildren
  '/gerencial/visita/$id/editar': typeof AuthenticatedGerencialVisitaIdEditarRoute
  '/visita/$id/orcamento/categorias': typeof AuthenticatedVisitaIdOrcamentoCategoriasRoute
  '/visita/$id/orcamento/blocos/$cat': typeof AuthenticatedVisitaIdOrcamentoBlocosCatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gerencial': typeof AuthenticatedGerencialRouteWithChildren
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/novo': typeof AuthenticatedNovoRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/gerencial/nova': typeof AuthenticatedGerencialNovaRoute
  '/_authenticated/projeto/$id': typeof AuthenticatedProjetoIdRoute
  '/_authenticated/visita/$id': typeof AuthenticatedVisitaIdRouteWithChildren
  '/_authenticated/visita/$id/orcamento': typeof AuthenticatedVisitaIdOrcamentoRouteWithChildren
  '/_authenticated/gerencial/visita/$id/editar': typeof AuthenticatedGerencialVisitaIdEditarRoute
  '/_authenticated/visita/$id/orcamento/categorias': typeof AuthenticatedVisitaIdOrcamentoCategoriasRoute
  '/_authenticated/visita/$id/orcamento/blocos/$cat': typeof AuthenticatedVisitaIdOrcamentoBlocosCatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/gerencial'
    | '/mapa'
    | '/novo'
    | '/perfil'
    | '/gerencial/nova'
    | '/projeto/$id'
    | '/visita/$id'
    | '/visita/$id/orcamento'
    | '/gerencial/visita/$id/editar'
    | '/visita/$id/orcamento/categorias'
    | '/visita/$id/orcamento/blocos/$cat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/gerencial'
    | '/mapa'
    | '/novo'
    | '/perfil'
    | '/gerencial/nova'
    | '/projeto/$id'
    | '/visita/$id'
    | '/visita/$id/orcamento'
    | '/gerencial/visita/$id/editar'
    | '/visita/$id/orcamento/categorias'
    | '/visita/$id/orcamento/blocos/$cat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/gerencial'
    | '/_authenticated/mapa'
    | '/_authenticated/novo'
    | '/_authenticated/perfil'
    | '/_authenticated/gerencial/nova'
    | '/_authenticated/projeto/$id'
    | '/_authenticated/visita/$id'
    | '/_authenticated/visita/$id/orcamento'
    | '/_authenticated/gerencial/visita/$id/editar'
    | '/_authenticated/visita/$id/orcamento/categorias'
    | '/_authenticated/visita/$id/orcamento/blocos/$cat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/novo': {
      id: '/_authenticated/novo'
      path: '/novo'
      fullPath: '/novo'
      preLoaderRoute: typeof AuthenticatedNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gerencial': {
      id: '/_authenticated/gerencial'
      path: '/gerencial'
      fullPath: '/gerencial'
      preLoaderRoute: typeof AuthenticatedGerencialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visita/$id': {
      id: '/_authenticated/visita/$id'
      path: '/visita/$id'
      fullPath: '/visita/$id'
      preLoaderRoute: typeof AuthenticatedVisitaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projeto/$id': {
      id: '/_authenticated/projeto/$id'
      path: '/projeto/$id'
      fullPath: '/projeto/$id'
      preLoaderRoute: typeof AuthenticatedProjetoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gerencial/nova': {
      id: '/_authenticated/gerencial/nova'
      path: '/nova'
      fullPath: '/gerencial/nova'
      preLoaderRoute: typeof AuthenticatedGerencialNovaRouteImport
      parentRoute: typeof AuthenticatedGerencialRoute
    }
    '/_authenticated/visita/$id/orcamento': {
      id: '/_authenticated/visita/$id/orcamento'
      path: '/orcamento'
      fullPath: '/visita/$id/orcamento'
      preLoaderRoute: typeof AuthenticatedVisitaIdOrcamentoRouteImport
      parentRoute: typeof AuthenticatedVisitaIdRoute
    }
    '/_authenticated/visita/$id/orcamento/categorias': {
      id: '/_authenticated/visita/$id/orcamento/categorias'
      path: '/categorias'
      fullPath: '/visita/$id/orcamento/categorias'
      preLoaderRoute: typeof AuthenticatedVisitaIdOrcamentoCategoriasRouteImport
      parentRoute: typeof AuthenticatedVisitaIdOrcamentoRoute
    }
    '/_authenticated/gerencial/visita/$id/editar': {
      id: '/_authenticated/gerencial/visita/$id/editar'
      path: '/visita/$id/editar'
      fullPath: '/gerencial/visita/$id/editar'
      preLoaderRoute: typeof AuthenticatedGerencialVisitaIdEditarRouteImport
      parentRoute: typeof AuthenticatedGerencialRoute
    }
    '/_authenticated/visita/$id/orcamento/blocos/$cat': {
      id: '/_authenticated/visita/$id/orcamento/blocos/$cat'
      path: '/blocos/$cat'
      fullPath: '/visita/$id/orcamento/blocos/$cat'
      preLoaderRoute: typeof AuthenticatedVisitaIdOrcamentoBlocosCatRouteImport
      parentRoute: typeof AuthenticatedVisitaIdOrcamentoRoute
    }
  }
}

interface AuthenticatedGerencialRouteChildren {
  AuthenticatedGerencialNovaRoute: typeof AuthenticatedGerencialNovaRoute
  AuthenticatedGerencialVisitaIdEditarRoute: typeof AuthenticatedGerencialVisitaIdEditarRoute
}

const AuthenticatedGerencialRouteChildren: AuthenticatedGerencialRouteChildren =
  {
    AuthenticatedGerencialNovaRoute: AuthenticatedGerencialNovaRoute,
    AuthenticatedGerencialVisitaIdEditarRoute:
      AuthenticatedGerencialVisitaIdEditarRoute,
  }

const AuthenticatedGerencialRouteWithChildren =
  AuthenticatedGerencialRoute._addFileChildren(
    AuthenticatedGerencialRouteChildren,
  )

interface AuthenticatedVisitaIdOrcamentoRouteChildren {
  AuthenticatedVisitaIdOrcamentoCategoriasRoute: typeof AuthenticatedVisitaIdOrcamentoCategoriasRoute
  AuthenticatedVisitaIdOrcamentoBlocosCatRoute: typeof AuthenticatedVisitaIdOrcamentoBlocosCatRoute
}

const AuthenticatedVisitaIdOrcamentoRouteChildren: AuthenticatedVisitaIdOrcamentoRouteChildren =
  {
    AuthenticatedVisitaIdOrcamentoCategoriasRoute:
      AuthenticatedVisitaIdOrcamentoCategoriasRoute,
    AuthenticatedVisitaIdOrcamentoBlocosCatRoute:
      AuthenticatedVisitaIdOrcamentoBlocosCatRoute,
  }

const AuthenticatedVisitaIdOrcamentoRouteWithChildren =
  AuthenticatedVisitaIdOrcamentoRoute._addFileChildren(
    AuthenticatedVisitaIdOrcamentoRouteChildren,
  )

interface AuthenticatedVisitaIdRouteChildren {
  AuthenticatedVisitaIdOrcamentoRoute: typeof AuthenticatedVisitaIdOrcamentoRouteWithChildren
}

const AuthenticatedVisitaIdRouteChildren: AuthenticatedVisitaIdRouteChildren = {
  AuthenticatedVisitaIdOrcamentoRoute:
    AuthenticatedVisitaIdOrcamentoRouteWithChildren,
}

const AuthenticatedVisitaIdRouteWithChildren =
  AuthenticatedVisitaIdRoute._addFileChildren(
    AuthenticatedVisitaIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGerencialRoute: typeof AuthenticatedGerencialRouteWithChildren
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedNovoRoute: typeof AuthenticatedNovoRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProjetoIdRoute: typeof AuthenticatedProjetoIdRoute
  AuthenticatedVisitaIdRoute: typeof AuthenticatedVisitaIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGerencialRoute: AuthenticatedGerencialRouteWithChildren,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedNovoRoute: AuthenticatedNovoRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProjetoIdRoute: AuthenticatedProjetoIdRoute,
  AuthenticatedVisitaIdRoute: AuthenticatedVisitaIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
